# Weeks 3 & 4 Assigments

***The Data Wrangling Workshop - Chapters 3 & 4***

*Exercise3.01 - Creating a Numpy Array (From a List)*

In [16]:
import numpy as np

In [18]:
list_1 = [1, 2, 3]
list_1

[1, 2, 3]

In [20]:
array_1 = np.array(list_1)

In [22]:
array_1

array([1, 2, 3])

In [24]:
a = np.array([1.2, 3.4, 5.6])
a

array([1.2, 3.4, 5.6])

In [26]:
type(a)

numpy.ndarray

In [28]:
type(array_1)

numpy.ndarray

In [30]:
type(list_1)

list

In [34]:
import os
os.getcwd()

'/Users/alkajohnson/Documents/GitHub/The-Data-Wrangling-Workshop/Chapter03'

In [36]:
data = np.genfromtxt('/Users/alkajohnson/Documents/GitHub/The-Data-Wrangling-Workshop/Chapter03/datasets/stock.csv',
                     delimiter=',', names=True,dtype=None, encoding='ascii')
#Key parameters of np.genfromtxt include:
#fname: The file name or file like object to read from
#delimiter: The string used to separate the values - if not specified, any consecutive whitespace acts as a delimiter
#dtype: Data type of the resulting array. If set to None, the data type will be inferred from the data
#names: If True, the first valid line after skip_header likes is treated as a list of column names
#encoding: This parameter is used to decode the string data in the file
data

array([('MMM', 100), ('AOS', 101), ('ABT', 102), ('ABBV', 103),
       ('ACN', 104), ('ATVI', 105), ('AYI', 106), ('ADBE', 107),
       ('AAP', 108), ('AMD', 109), ('AES', 110), ('AET', 111),
       ('AMG', 112), ('AFL', 113), ('A', 114), ('APD', 115),
       ('AKAM', 116), ('ALK', 117), ('ALB', 118), ('ARE', 119),
       ('ALXN', 120), ('ALGN', 121), ('ALLE', 122), ('AGN', 123),
       ('ADS', 124), ('LNT', 125), ('ALL', 126), ('GOOGL', 127),
       ('GOOG', 128), ('MO', 129), ('AMZN', 130), ('AEE', 131),
       ('AAL', 132), ('AEP', 133), ('AXP', 134), ('AIG', 135),
       ('AMT', 136), ('AWK', 137), ('AMP', 138), ('ABC', 139),
       ('AME', 140), ('AMGN', 141), ('APH', 142), ('APC', 143),
       ('ADI', 144), ('ANDV', 145), ('ANSS', 146), ('ANTM', 147),
       ('AON', 148)], dtype=[('Symbol', '<U5'), ('Price', '<i8')])

In [38]:
type(data)

numpy.ndarray

*Exercise 3.02: Adding Two Numpy Arrays*

In [42]:
list_2 = list_1 + list_1
list_2

[1, 2, 3, 1, 2, 3]

In [44]:
array_2 = array_1 + array_1
array_2

array([2, 4, 6])

In [62]:
numbers = np.genfromtxt('/Users/alkajohnson/Documents/GitHub/The-Data-Wrangling-Workshop/Chapter03/datasets/numbers.csv',
                        delimiter=',', names=True)
numbers = numbers.astype('float64')
numbers + numbers
#.astype() is a method used to explicitly change the data type of an array or a column. This method creates a copy of the data by default leaving the original unchanged

array([202., 204., 206., 208., 210., 212., 214., 216., 218., 220., 222.,
       224., 226., 228., 230., 232., 234., 236., 238., 240., 242., 244.,
       246., 248., 250., 252., 254., 256., 258., 260., 262., 264., 266.,
       268., 270., 272., 274., 276., 278., 280., 282., 284., 286., 288.,
       290., 292., 294., 296.])

*Exercise 3.03: Mathematical Operations on Numpy Arrays*

In [65]:
numbers * 45

array([4545., 4590., 4635., 4680., 4725., 4770., 4815., 4860., 4905.,
       4950., 4995., 5040., 5085., 5130., 5175., 5220., 5265., 5310.,
       5355., 5400., 5445., 5490., 5535., 5580., 5625., 5670., 5715.,
       5760., 5805., 5850., 5895., 5940., 5985., 6030., 6075., 6120.,
       6165., 6210., 6255., 6300., 6345., 6390., 6435., 6480., 6525.,
       6570., 6615., 6660.])

In [67]:
numbers / 67.7

array([1.49187592, 1.50664697, 1.52141802, 1.53618907, 1.55096012,
       1.56573117, 1.58050222, 1.59527326, 1.61004431, 1.62481536,
       1.63958641, 1.65435746, 1.66912851, 1.68389956, 1.69867061,
       1.71344165, 1.7282127 , 1.74298375, 1.7577548 , 1.77252585,
       1.7872969 , 1.80206795, 1.816839  , 1.83161004, 1.84638109,
       1.86115214, 1.87592319, 1.89069424, 1.90546529, 1.92023634,
       1.93500739, 1.94977843, 1.96454948, 1.97932053, 1.99409158,
       2.00886263, 2.02363368, 2.03840473, 2.05317578, 2.06794682,
       2.08271787, 2.09748892, 2.11225997, 2.12703102, 2.14180207,
       2.15657312, 2.17134417, 2.18611521])

In [69]:
array_1**array_1

array([ 1,  4, 27])

In [71]:
numbers**2

array([10201., 10404., 10609., 10816., 11025., 11236., 11449., 11664.,
       11881., 12100., 12321., 12544., 12769., 12996., 13225., 13456.,
       13689., 13924., 14161., 14400., 14641., 14884., 15129., 15376.,
       15625., 15876., 16129., 16384., 16641., 16900., 17161., 17424.,
       17689., 17956., 18225., 18496., 18769., 19044., 19321., 19600.,
       19881., 20164., 20449., 20736., 21025., 21316., 21609., 21904.])

*Exercise 3.04: Advanced Mathematical Operations on Numpy Arrays*

In [74]:
import pandas as pd

In [78]:
#Tried doing this with the numbers variable already set but got AttributeError: 'numpy.ndarray' object has no attribute 'values'
df = pd.read_csv('/Users/alkajohnson/Documents/GitHub/The-Data-Wrangling-Workshop/Chapter03/datasets/numbers.csv')
list_5 = df.values.tolist()
list_5

[[101],
 [102],
 [103],
 [104],
 [105],
 [106],
 [107],
 [108],
 [109],
 [110],
 [111],
 [112],
 [113],
 [114],
 [115],
 [116],
 [117],
 [118],
 [119],
 [120],
 [121],
 [122],
 [123],
 [124],
 [125],
 [126],
 [127],
 [128],
 [129],
 [130],
 [131],
 [132],
 [133],
 [134],
 [135],
 [136],
 [137],
 [138],
 [139],
 [140],
 [141],
 [142],
 [143],
 [144],
 [145],
 [146],
 [147],
 [148]]

In [80]:
array_5 = np.array(list_5)
array_5

array([[101],
       [102],
       [103],
       [104],
       [105],
       [106],
       [107],
       [108],
       [109],
       [110],
       [111],
       [112],
       [113],
       [114],
       [115],
       [116],
       [117],
       [118],
       [119],
       [120],
       [121],
       [122],
       [123],
       [124],
       [125],
       [126],
       [127],
       [128],
       [129],
       [130],
       [131],
       [132],
       [133],
       [134],
       [135],
       [136],
       [137],
       [138],
       [139],
       [140],
       [141],
       [142],
       [143],
       [144],
       [145],
       [146],
       [147],
       [148]])

In [82]:
np.sin(array_5)

array([[ 0.45202579],
       [ 0.99482679],
       [ 0.62298863],
       [-0.3216224 ],
       [-0.97053528],
       [-0.7271425 ],
       [ 0.18478174],
       [ 0.92681851],
       [ 0.81674261],
       [-0.04424268],
       [-0.86455145],
       [-0.8899956 ],
       [-0.09718191],
       [ 0.78498039],
       [ 0.94543533],
       [ 0.23666139],
       [-0.68969794],
       [-0.98195217],
       [-0.3714041 ],
       [ 0.58061118],
       [ 0.99881522],
       [ 0.49871315],
       [-0.45990349],
       [-0.99568699],
       [-0.61604046],
       [ 0.32999083],
       [ 0.97263007],
       [ 0.72103771],
       [-0.19347339],
       [-0.93010595],
       [-0.81160339],
       [ 0.05308359],
       [ 0.86896576],
       [ 0.88592482],
       [ 0.08836869],
       [-0.79043321],
       [-0.94251445],
       [-0.22805226],
       [ 0.69608013],
       [ 0.98023966],
       [ 0.36317137],
       [-0.58779501],
       [-0.99834536],
       [-0.49102159],
       [ 0.46774516],
       [ 0

In [84]:
np.log(array_5)

array([[4.61512052],
       [4.62497281],
       [4.63472899],
       [4.6443909 ],
       [4.65396035],
       [4.66343909],
       [4.67282883],
       [4.68213123],
       [4.69134788],
       [4.70048037],
       [4.7095302 ],
       [4.71849887],
       [4.72738782],
       [4.73619845],
       [4.74493213],
       [4.75359019],
       [4.76217393],
       [4.77068462],
       [4.77912349],
       [4.78749174],
       [4.79579055],
       [4.80402104],
       [4.81218436],
       [4.82028157],
       [4.82831374],
       [4.83628191],
       [4.84418709],
       [4.85203026],
       [4.8598124 ],
       [4.86753445],
       [4.87519732],
       [4.88280192],
       [4.89034913],
       [4.8978398 ],
       [4.90527478],
       [4.91265489],
       [4.91998093],
       [4.92725369],
       [4.93447393],
       [4.94164242],
       [4.94875989],
       [4.95582706],
       [4.96284463],
       [4.9698133 ],
       [4.97673374],
       [4.98360662],
       [4.99043259],
       [4.997

In [86]:
np.exp(array_5)

array([[7.30705998e+43],
       [1.98626484e+44],
       [5.39922761e+44],
       [1.46766223e+45],
       [3.98951957e+45],
       [1.08446386e+46],
       [2.94787839e+46],
       [8.01316426e+46],
       [2.17820388e+47],
       [5.92097203e+47],
       [1.60948707e+48],
       [4.37503945e+48],
       [1.18925902e+49],
       [3.23274119e+49],
       [8.78750164e+49],
       [2.38869060e+50],
       [6.49313426e+50],
       [1.76501689e+51],
       [4.79781333e+51],
       [1.30418088e+52],
       [3.54513118e+52],
       [9.63666567e+52],
       [2.61951732e+53],
       [7.12058633e+53],
       [1.93557604e+54],
       [5.26144118e+54],
       [1.43020800e+55],
       [3.88770841e+55],
       [1.05678871e+56],
       [2.87264955e+56],
       [7.80867107e+56],
       [2.12261687e+57],
       [5.76987086e+57],
       [1.56841351e+58],
       [4.26338995e+58],
       [1.15890954e+59],
       [3.15024275e+59],
       [8.56324762e+59],
       [2.32773204e+60],
       [6.32743171e+60],


*Exercise 3.05: Generating Arrays Using Arange and Linspace Methods*

In [99]:
#np.arange() creates an array of evenly spaced values within a given interval.
#syntax np.arange(start, stop, interval count) if interval count not given goes by 1
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
print("Numbers spaced apart by 2: ", np.arange(0,11,2))
print("Numbers spaced apart by a floating point number: ", np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ", np.arange(30, -1, -5))

Numbers spaced apart by 2:  [ 0  2  4  6  8 10]
Numbers spaced apart by a floating point number:  [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]


In [105]:
#np.linspace() creates an array of evenly spaced values within a specified range
#syntax - np.linspace(start, stop, num, endpoint, retstep, dtype)
#num - The number of samples to generate (default is 50)
print("11 linearly spaced numbers between 1 and 5: ", np.linspace(1,5,11))

11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


*Exercise 3.06: Creating Multi-Dimensional Arrays*

In [112]:
df2 = pd.read_csv('/Users/alkajohnson/Documents/GitHub/The-Data-Wrangling-Workshop/Chapter03/datasets/numbers2.csv',
                  header=None)
list_2D = df2.values
mat1 = np.array(list_2D)
print("Type/Class of this object:", type(mat1))
print("Here is the matrix\n-------------\n", mat1, "\n---------------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
-------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
---------------


In [116]:
tuple_2D = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(tuple_2D)
print(mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


*Exercise 3.07: The Dimension, Shape, Size, and Data Type of Two-Dimensional Arrays*

In [119]:
#Shape - number of rows, number of columns
#Size = rows of numbers * number of columns
print("Dimension of this matrix: ", mat1.ndim,sep=' ')

Dimension of this matrix:  2


In [121]:
print("Size of this matrix: ", mat1.size,sep=' ')

Size of this matrix:  9


In [123]:
print("Shape of this matrix: ", mat1.shape,sep=' ')

Shape of this matrix:  (3, 3)


In [125]:
print("Data type of this matrix: ", mat1.dtype,sep=' ')

Data type of this matrix:  int64


*Exercise 3.08: Zeros, Ones, Random, Identity Matrices, and Vectors*

In [128]:
#an identity matrix is a matrix filled with zeros and ones in a diagonal from left to right
print("Vector of zeros: ",np.zeros(5))

Vector of zeros:  [0. 0. 0. 0. 0.]


In [140]:
print("Matrix of zeros: \n",np.zeros((3,4)))

Matrix of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [138]:
print("Matrix of 5's: \n",5*np.ones((3,3)))

Matrix of 5's: 
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [142]:
print("Identity matrix of dimension 2:\n", np.eye(2))

Identity matrix of dimension 2:
 [[1. 0.]
 [0. 1.]]


In [144]:
print("Identity matrix of dimension 4:\n", np.eye(4))

Identity matrix of dimension 4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [146]:
print("Random matrix of shape(4,3):\n", np.random.randint(low=1,high=10,size=(4,3)))

Random matrix of shape(4,3):
 [[1 8 8]
 [1 4 1]
 [1 5 6]
 [9 4 6]]


*Exercise 3.09: Reshaping, Ravel, Min, Max, and Sorting*

In [149]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)

In [153]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [157]:
print("a looks like\n",a)
print("b looks like\n",b)
print("c looks like\n",c)

a looks like
 [62 51 12 57 55 86 29 72 89 29 80 38 68 94 41 42 23 57 76 95 73  2  1 83
  6 78 61 98 16 81]
b looks like
 [[[62 51 12 57 55]
  [86 29 72 89 29]
  [80 38 68 94 41]]

 [[42 23 57 76 95]
  [73  2  1 83  6]
  [78 61 98 16 81]]]
c looks like
 [[62 51 12 57 55]
 [86 29 72 89 29]
 [80 38 68 94 41]
 [42 23 57 76 95]
 [73  2  1 83  6]
 [78 61 98 16 81]]


In [161]:
b_flat = b.ravel()
print(b_flat)

[62 51 12 57 55 86 29 72 89 29 80 38 68 94 41 42 23 57 76 95 73  2  1 83
  6 78 61 98 16 81]
